[package]
name = "ferrik"
version = "0.1.0"
authors = ["Ops Fox <opsfox245@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
cgmath = "0.18.0"